"""Add user_settings table

Revision ID: 2c3960f86b3e
Revises: f37d8d3c472c
Create Date: 2026-02-12 20:28:36.558194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3960f86b3e'
down_revision = 'f37d8d3c472c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_algorithm', sa.String(length=64), nullable=True),
    sa.Column('default_algorithm_params', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_snapshot_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_snapshots_per_playlist', sa.Integer(), nullable=False),
    sa.Column('dashboard_show_recent_activity', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    # ### end Alembic commands ###
