"""Add playlist_snapshots table

Revision ID: 5c6c7c0845ac
Revises: 2c3960f86b3e
Create Date: 2026-02-12 21:16:46.016867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6c7c0845ac'
down_revision = '2c3960f86b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=255), nullable=False),
    sa.Column('playlist_name', sa.String(length=255), nullable=False),
    sa.Column('track_uris_json', sa.Text(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_snapshots_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_snapshots_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_snapshot_user_playlist_created', ['user_id', 'playlist_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_user_playlist_created')
        batch_op.drop_index(batch_op.f('ix_playlist_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_snapshots_playlist_id'))

    op.drop_table('playlist_snapshots')
    # ### end Alembic commands ###
