"""Initial schema: users, workshop_sessions, upstream_sources, schedules, job_executions

Revision ID: aa2823fcd4b0
Revises: 
Create Date: 2026-02-12 10:00:01.123263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2823fcd4b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_spotify_id'), ['spotify_id'], unique=True)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('target_playlist_id', sa.String(length=64), nullable=False),
    sa.Column('target_playlist_name', sa.String(length=255), nullable=True),
    sa.Column('source_playlist_ids', sa.JSON(), nullable=True),
    sa.Column('algorithm_name', sa.String(length=64), nullable=True),
    sa.Column('algorithm_params', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.String(length=10), nullable=False),
    sa.Column('schedule_value', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('upstream_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_playlist_id', sa.String(length=255), nullable=False),
    sa.Column('source_playlist_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upstream_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upstream_sources_target_playlist_id'), ['target_playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upstream_sources_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_upstream_user_target', ['user_id', 'target_playlist_id'], unique=False)

    op.create_table('workshop_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=255), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('track_uris_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workshop_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshop_sessions_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_workshop_user_playlist', ['user_id', 'playlist_id'], unique=False)

    op.create_table('job_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracks_added', sa.Integer(), nullable=True),
    sa.Column('tracks_total', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_executions_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_executions_schedule_id'))

    op.drop_table('job_executions')
    with op.batch_alter_table('workshop_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_workshop_user_playlist')
        batch_op.drop_index(batch_op.f('ix_workshop_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_sessions_playlist_id'))

    op.drop_table('workshop_sessions')
    with op.batch_alter_table('upstream_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_upstream_user_target')
        batch_op.drop_index(batch_op.f('ix_upstream_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_upstream_sources_target_playlist_id'))

    op.drop_table('upstream_sources')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_user_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_spotify_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
