"""Add login tracking and Spotify profile fields to User model

Revision ID: e2c728c936de
Revises: aa2823fcd4b0
Create Date: 2026-02-12 10:24:38.696309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c728c936de'
down_revision = 'aa2823fcd4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('country', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('spotify_product', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('spotify_uri', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spotify_uri')
        batch_op.drop_column('spotify_product')
        batch_op.drop_column('country')
        batch_op.drop_column('is_active')
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
