name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      
      - name: Run tests
        run: pytest
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Build Docker image
        run: |
          docker build -t shuffify:${{ github.ref }} .
      
      - name: Deploy to Production
        if: github.ref == 'refs/tags/v*'
        run: |
          # Add your deployment steps here
          # For example:
          # - Push to Docker registry
          # - Deploy to cloud provider
          echo "Deploying version ${{ github.ref }} to production" 